In [1]:
import tensorflow_decision_forests as tfdf
import pandas as pd
import numpy as np

In [2]:
ds_train = pd.read_csv('train.csv')
ds_test = pd.read_csv('test.csv')

In [3]:
print (ds_train.dtypes)

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [4]:
object_columns = ds_train.select_dtypes(include=['object']).columns
print(object_columns)

object_columns_test = ds_test.select_dtypes(include=['object']).columns
print(object_columns_test)

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')
Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [5]:
#for column in ds_train.columns:
 #   print(column, ds_train[column].nunique())

In [6]:
#len(object_columns)

In [7]:
col_dummy = []
for column in ds_train.columns:
    if ds_train[column].nunique()==2:
        col_dummy.append(column)
print(col_dummy)

['Street', 'Alley', 'Utilities', 'CentralAir']

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for column in col_dummy:
    ds_train[column] = le.fit_transform(ds_train[column])
    ds_test[column] = le.fit_transform(ds_test[column])

In [9]:
#print(ds_train)

In [10]:
object_columns = [item for item in object_columns if item not in col_dummy]

In [11]:
print(object_columns)

['MSZoning', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

In [12]:
le = LabelEncoder()
for column in object_columns:
    ds_train[column] = le.fit_transform(ds_train[column])
    ds_test[column] = le.fit_transform(ds_test[column])

In [13]:
ds_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,2,3,3,0,...,0,3,4,4,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,2,3,3,0,...,0,3,4,4,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,2,0,3,0,...,0,3,4,4,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,2,0,3,0,...,0,3,4,4,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,2,0,3,0,...,0,3,4,4,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,2,3,3,0,...,0,3,4,4,0,8,2007,8,4,175000
1456,1457,20,3,85.0,13175,1,2,3,3,0,...,0,3,2,4,0,2,2010,8,4,210000
1457,1458,70,3,66.0,9042,1,2,3,3,0,...,0,3,0,2,2500,5,2010,8,4,266500
1458,1459,20,3,68.0,9717,1,2,3,3,0,...,0,3,4,4,0,4,2010,8,4,142125
1459,1460,20,3,75.0,9937,1,2,3,3,0,...,0,3,4,4,0,6,2008,8,4,147500

In [14]:
columns_with_missing = ds_train.columns[ds_train.isnull().any()]
print(columns_with_missing)

Index(['LotFrontage', 'MasVnrArea', 'GarageYrBlt'], dtype='object')

In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(ds_train[columns_with_missing])
ds_train[columns_with_missing] = imputer.transform(ds_train[columns_with_missing])

In [16]:
ds_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,2,3,3,0,...,0,3,4,4,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,2,3,3,0,...,0,3,4,4,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,2,0,3,0,...,0,3,4,4,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,2,0,3,0,...,0,3,4,4,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,2,0,3,0,...,0,3,4,4,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,2,3,3,0,...,0,3,4,4,0,8,2007,8,4,175000
1456,1457,20,3,85.0,13175,1,2,3,3,0,...,0,3,2,4,0,2,2010,8,4,210000
1457,1458,70,3,66.0,9042,1,2,3,3,0,...,0,3,0,2,2500,5,2010,8,4,266500
1458,1459,20,3,68.0,9717,1,2,3,3,0,...,0,3,4,4,0,4,2010,8,4,142125
1459,1460,20,3,75.0,9937,1,2,3,3,0,...,0,3,4,4,0,6,2008,8,4,147500

In [17]:
X = ds_train.iloc[:, :-1].values
y = ds_train.iloc[:, -1].values

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [19]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [20]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[214720.  200624. ]
 [146515.  133000. ]
 [104830.  110000. ]
 [224747.9 192000. ]
 [ 91230.   88000. ]
 [116607.5  85000. ]
 [244962.8 282922. ]
 [132650.  141000. ]
 [649000.  745000. ]
 [155305.  148800. ]
 [216624.  208900. ]
 [133720.  136905. ]
 [240929.9 225000. ]
 [122290.  123000. ]
 [138100.  119200. ]
 [153760.  145000. ]
 [215160.  190000. ]
 [121590.  123600. ]
 [138390.  149350. ]
 [194352.5 155000. ]
 [131890.  166000. ]
 [142050.  144500. ]
 [115345.  110000. ]
 [160300.  174000. ]
 [174205.  185000. ]
 [226130.  168000. ]
 [167950.  177500. ]
 [ 92000.   84500. ]
 [318190.  320000. ]
 [111020.  118500. ]
 [140570.  110000. ]
 [199390.  213000. ]
 [139390.  156000. ]
 [278516.8 250000. ]
 [340282.4 372500. ]
 [185164.  175000. ]
 [282658.3 277500. ]
 [128225.  112500. ]
 [230031.  263000. ]
 [296471.3 325000. ]
 [185340.  243000. ]
 [117990.  130000. ]
 [171599.  164990. ]
 [301176.8 280000. ]
 [326946.8 403000. ]
 [147300.  119000. ]
 [130140.  125000. ]
 [128625.8 128200. ]
 [168615.  172500. ]
 [105008.8  84900. ]
 [356958.6 412500. ]
 [145180.  156000. ]
 [171493.2 167900. ]
 [ 92716.6 100000. ]
 [254780.  275000. ]
 [110303.3 123000. ]
 [146990.  132000. ]
 [257590.  239900. ]
 [129030.  139000. ]
 [110550.  115000. ]
 [146300.  137500. ]
 [143395.  135000. ]
 [135590.  134450. ]
 [151240.  180500. ]
 [192665.  193500. ]
 [167440.  156500. ]
 [119422.5 132000. ]
 [218081.5 224500. ]
 [128140.  139000. ]
 [185281.  225000. ]
 [190330.5 188500. ]
 [123190.  118000. ]
 [ 78680.   82000. ]
 [228886.1 392000. ]
 [101990.8 112000. ]
 [270364.7 248900. ]
 [129496.  134500. ]
 [105590.   79500. ]
 [262654.9 320000. ]
 [164200.  158000. ]
 [143845.  140000. ]
 [123538.3 136500. ]
 [122863.4 107500. ]
 [141120.  145000. ]
 [185320.  200500. ]
 [206100.  185000. ]
 [ 99230.  105000. ]
 [206015.  202665. ]
 [172263.2 186000. ]
 [139025.  136000. ]
 [193350.  200500. ]
 [185235.  190000. ]
 [182136.5 187500. ]
 [221201.  200000. ]
 [170579.  172500. ]
 [143970.  157000. ]
 [209390.  213000. ]
 [172430.  185000. ]
 [122900.  124500. ]
 [141243.2 162900. ]
 [253300.  260000. ]
 [253834.9 198500. ]
 [117990.  120000. ]
 [167393.2 159500. ]
 [112480.  105900. ]
 [293442.6 260000. ]
 [138300.  143000. ]
 [101675.  106500. ]
 [171687.  178900. ]
 [114020.  127000. ]
 [ 83176.4  90350. ]
 [128965.  118500. ]
 [193025.  190000. ]
 [116340.  119900. ]
 [164644.  183900. ]
 [157650.  155000. ]
 [404774.3 386250. ]
 [131080.  133000. ]
 [183090.  193500. ]
 [247830.  270000. ]
 [162585.  141000. ]
 [154715.2 146000. ]
 [137140.  128500. ]
 [233758.  176000. ]
 [235880.  214000. ]
 [228999.3 222000. ]
 [376898.9 415298. ]
 [180031.  187750. ]
 [185424.5 199900. ]
 [172105.  180000. ]
 [212261.5 206300. ]
 [184666.5 194000. ]
 [144542.8 142953. ]
 [204030.  182900. ]
 [106050.4 116050. ]
 [224872.8 213250. ]
 [127400.  139500. ]
 [189804.9 179000. ]
 [108150.8 107900. ]
 [181890.  175900. ]
 [142383.  158500. ]
 [131200.  145000. ]
 [217797.  217000. ]
 [152510.  150500. ]
 [154900.  108959. ]
 [176370.  165600. ]
 [236696.1 201000. ]
 [139835.  145500. ]
 [299951.2 319900. ]
 [228240.  215000. ]
 [166140.  180500. ]
 [368133.2 367294. ]
 [300820.  239000. ]
 [157540.  145900. ]
 [206240.  161000. ]
 [243720.  250000. ]
 [111700.   89471. ]
 [226462.8 230000. ]
 [147148.  147000. ]
 [175693.4 163900. ]
 [120315.   97000. ]
 [143930.  142000. ]
 [198607.5 197000. ]
 [113825.  129000. ]
 [250825.6 232000. ]
 [114729.3 115000. ]
 [161400.  175000. ]
 [291100.  265000. ]
 [198294.  207000. ]
 [182745.  181000. ]
 [173440.  176000. ]
 [161380.  171000. ]
 [175553.2 196000. ]
 [175370.  176000. ]
 [115380.1 113000. ]
 [105376.4 139000. ]
 [136920.  135000. ]
 [228330.  240000. ]
 [126300.  112000. ]
 [153360.  134000. ]
 [307893.5 316600. ]
 [218180.  170000. ]
 [114067.6 116000. ]
 [316206.9 306000. ]
 [125765.8  82500. ]
 [179580.  175000. ]
 [104150.  106000. ]
 [193048.  194000. ]
 [167720.5 194201. ]
 [138600.  155900. ]
 [135850.  138000. ]
 [146075.  177000. ]
 [215880.  214000. ]
 [132075.  148000. ]
 [124650.  127000. ]
 [139240.  142500. ]
 [ 93690.   80000. ]
 [129110.  145000. ]
 [172795.  171000. ]
 [132665.  122500. ]
 [134375.  139000. ]
 [202406.1 189000. ]
 [108578.3 120500. ]
 [136395.  124000. ]
 [147108.7 160000. ]
 [167750.  200000. ]
 [146590.  160000. ]
 [328171.4 313000. ]
 [256059.3 275000. ]
 [ 77700.   67000. ]
 [144430.  159000. ]
 [268697.7 251000. ]
 [ 91140.   92900. ]
 [103550.  109500. ]
 [374606.3 385000. ]
 [187300.  129000. ]
 [196398.   82500. ]
 [253009.  301000. ]
 [255305.4 249700. ]
 [ 93980.   81000. ]
 [225840.  187500. ]
 [176093.2 110000. ]
 [131313.4 117000. ]
 [111388.3 128500. ]
 [189899.  213490. ]
 [251640.  284000. ]
 [241253.  230500. ]
 [208397.  190000. ]
 [127950.  135000. ]
 [181055.5 152000. ]
 [ 90510.   87500. ]
 [145990.  155000. ]
 [105434.1 115000. ]
 [149550.  144000. ]
 [225785.  248000. ]
 [137787.5 132500. ]
 [139525.  136000. ]
 [117490.  117000. ]
 [ 81260.   82000. ]
 [197550.  157500. ]
 [101860.  110000. ]
 [186400.  181000. ]
 [200390.  192500. ]
 [215827.5 223500. ]
 [167600.  181500. ]
 [188990.  170000. ]
 [212270.  187500. ]
 [192050.  185900. ]
 [125155.  160000. ]
 [202150.  192000. ]
 [183400.  181900. ]
 [245552.8 266000. ]
 [ 92260.   99900. ]
 [397852.5 438780. ]
 [237550.  229456. ]
 [229915.1 216837. ]
 [ 95500.  110500. ]
 [204795.6 175900. ]
 [406445.3 538000. ]
 [494226.4 160000. ]
 [220157.7 172500. ]
 [138880.  108000. ]
 [139650.  131500. ]
 [ 90050.  106250. ]
 [418037.2 385000. ]
 [330465.9 370878. ]
 [372825.  345000. ]
 [ 78740.   68500. ]
 [230200.  250000. ]
 [236004.  245350. ]
 [139480.  125000. ]
 [246170.  234000. ]
 [141250.  145000. ]
 [177250.  181000. ]
 [127188.7 104000. ]
 [227910.  233000. ]
 [239112.8 164000. ]
 [176335.  219500. ]
 [224972.5 195000. ]
 [116310.  108000. ]
 [136400.  149900. ]
 [396120.1 315000. ]
 [174710.  177500. ]
 [161000.  140000. ]
 [182073.5 193879. ]
 [174940.  137900. ]
 [116260.  118000. ]
 [349240.  324000. ]
 [450342.7 555000. ]
 [146388.7 136000. ]
 [ 78930.   82500. ]
 [ 94830.4 101000. ]]

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8400670170795789

In [22]:
columns_with_missing_test = ds_test.columns[ds_test.isnull().any()]
print(columns_with_missing_test)

Index(['LotFrontage', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'GarageYrBlt',
       'GarageCars', 'GarageArea'],
      dtype='object')

In [23]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(ds_test[columns_with_missing_test])
ds_test[columns_with_missing_test] = imputer.transform(ds_test[columns_with_missing_test])

In [24]:
X_test_to_know = ds_test.iloc[:, :].values

In [25]:
y_pred_final = regressor.predict(X_test_to_know)
np.set_printoptions(precision=2)
print(y_pred_final)

[121865.  156690.  178975.  ... 154312.5 110650.  216601. ]

In [26]:
X_test_to_know[:, 0]

array([1461., 1462., 1463., ..., 2917., 2918., 2919.])

In [27]:
submission = pd.DataFrame(data = {'Id': (X_test_to_know[:, 0]).astype(int),
                                'SalePrice': y_pred_final})

submission.to_csv('predicted_prices_submission.csv', index=False)

In [28]:
submission

        Id  SalePrice
0     1461   121865.0
1     1462   156690.0
2     1463   178975.0
3     1464   179470.0
4     1465   206580.0
...    ...        ...
1454  2915    92400.0
1455  2916    85090.0
1456  2917   154312.5
1457  2918   110650.0
1458  2919   216601.0

[1459 rows x 2 columns]